project:
  type: website

website:
  title: "G3RT-Tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - tutorial_01.qmd
      - tutorial_02.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  cache: true


