project:
  type: website

bibliography: bibliography.bib
bibliographystyle: apa
number-sections: true

website:
  title: "G3RT-Tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - tutorial_01.qmd
      - tutorial_02.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: right
    html-math-method: katex
    link-external-icon: true
    #mainfont: Georgia
    fontsize: 14px
  pdf:
    toc: true
    colorlinks: true
    mainfont: "Times New Roman"
    monofont: "JuliaMono"

execute:
  cache: true


